config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #when receive get request with / url we invoke index action within
  #home controller
  # get '/' => 'home#index', as: :home
  root 'home#index'
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]
  get '/auth/twitter', as: :sign_in_with_twitter
  get '/auth/twitter/callback' => 'callbacks#twitter'
  namespace :admin do
    resources :questions
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :questions, only: [:index, :show, :create]
    end
  end


  get '/contact' => 'home#contact'
  post '/contact_submit' => 'home#contact_submit'
  resources :users, only: [:create, :new]
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :questions, shallow: true do
    # get :search, on: :collection
    # get :flag, on: :member
    # post :approve
    resources :answers, only: [:create, :destroy] do
      resources :comments, only: [:create, :destroy]
    end

    resources :likes, only: [:create, :destroy]
    resources :votes, only: [:create, :destroy, :update]

  end
  # get '/questions/new'  => 'questions#new', as: :new_question
  # post({'/questions'    => 'questions#create', as: :questions})
  # get '/questions/:id'  => 'questions#show', as: :question
  # get '/questions'      => 'questions#index'
  #
  # get '/questions/:id/edit' => 'questions#edit', as: :edit_question
  # patch '/questions/:id' => 'questions#update'
  # delete '/questions/:id' =>'questions#destroy'

end

app/models/question.rb
class Question < ApplicationRecord
  attr_reader :tweet_this
  belongs_to :user
  has_many :answers, -> { order(created_at: :DESC) }, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user
  has_many :votes, dependent: :destroy
  has_many :voters, through: :votes, source: :user
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates :title, presence: true, uniqueness: {case_sensative: false,
                                                 message: 'must be unique'}
  validates :body, length: { minimum: 5},
                   uniqueness: { scope: :title }
  validates :view_count, numericality: {greater_than_or_equal_to: 0}
  after_initialize :set_defaults
  before_validation :titleize_title

  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  mount_uploader :image, ImageUploader

  def tweet_this=(value)
   @tweet_this = ActiveRecord::Type::Boolean.new.cast(value)
  end

  def self.recent_ten
    limit(10).order(created_at: :desc)
  end

  def user_full_name
    user ? user.full_name : 'Anonymous'
  end

  def user_first_name
    user ? user.first_name : 'Anonymous'
  end

  def user_last_name
    user ? user.last_name : 'Anonymous'
  end

  def like_for(user)
    likes.find_by(user: user)
  end

  def vote_value
    votes.up.count - votes.down.count
  end

  # def to_param
  #   "#{id}-#{title}".parameterize
  # end

  private
  def set_defaults
    self.view_count ||=0
  end
  def titleize_title
    self.title = self.title.titleize if title.presence
  end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::BaseController

  def index
    @questions = Question.order(created_at: :desc).limit(10)
    # render json: questions.to_json
    # would bypass templates so comment out
  end

  def show
    question = Question.friendly.find(params[:id])
    render json: question
  end

  def create
    question_params = params.require(:question).permit(:title, :body)
    question = Question.new question_params
    question.user = @api_user
    if question.save
      render json: {id: question.id, status: :success}
    else
    render json: {status: :failure, errors: question.errors.full_messages}
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  #perform method before actions
  before_action :authenticate_user, except: [:index, :show]
  before_action :find_question, only: [:edit, :update, :destroy, :show]
  before_action :authorize_access, only: [:edit, :update, :destroy]

  def new
    @question = Question.new
  end

  def create
    #Question.create params[:question] failed access
    @question = Question.new question_params
    @question.user = current_user
    if @question.save
      if current_user.signed_in_with_twitter?
        client = Twitter::REST::Client.new do |config|
          config.consumer_key        = ENV['TWITTER_CONSUMER_KEY']
          config.consumer_secret     = ENV['TWITTER_CONSUMER_SECRET']
          config.access_token        = current_user.oauth_token
          config.access_token_secret = current_user.oauth_secret
        end
        client.update @question.title
      end
      # flash[:notice] = 'Question Created'
      redirect_to question_path(@question), notice: 'Question Created'
    else
      flash.now[:alert] = 'Please see errors below!'
      render :new
    end
  end

  def show
    @answer = Answer.new
    @like = @question.like_for(current_user)
    respond_to do |format|
      format.html {render}
      format.text {render}
      format.xml {render xml: @question}
      format.json {render json: @question.to_json}
    end
  end

  def index
    @questions = Question.order(created_at: :desc).page(params[:page]).per(10)
    respond_to do |format|
      format.html {render}
      format.text {render}
      format.xml {render xml: @questions}
      format.json {render json: @questions.to_json}
    end
  end

  def edit
  end

  # Capture the parameters from the form submission
  # from the edit action in order to update a question
  # URL: /questions/:id/update
  # METHOD: PATCH
  def update
    @question.slug = nil
    if @question.update question_params
      redirect_to question_path(@question)
    else
      render :edit
    end
  end

  #Destroy questions action
  #URL: /questoions/:id/destroy
  #METHOD: PATCH
  def destroy
    @question.destroy
    redirect_to questions_path, notice: 'Question deleted'
  end

  private
  def question_params
    params.require(:question).permit([:title,
                                      :body,
                                      :tweet_this,
                                      :image, 
                                      tag_ids: []])
  end

  def find_question
    @question = Question.friendly.find(params[:id])

  end

  def authorize_access
    unless can? :manage, @question
    # unless (current_user == @question.user || current_user.admin?)
      # head :unauthorized # this will send an empty HTTP response with 401 code
      redirect_to root_path, alert: 'Access Denied'
    end
  end
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/api/v1/questions_helper.rb
module Api::V1::QuestionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-8 col-sm-offset-1">
    <!--<div class="errors"><%= @question.errors.full_messages.join(', ') %>
    </div> -->
    <%# We use form_for when we're creating a form related to a Rails model. the
        first argument of the form_for must be an ActiveRecord object.
        if the first argument is a new instance of the ActiveRecord class, for
        example, Question.new then the form will automatically send a POST request
        to the standard create action url which is in this case: questions_path %>
    <%= simple_form_for @question do |f| %>
        <%= f.input :title %>
        <%= f.input :body %>
        <%= f.input :image %>

        <%= f.collection_select(
          :tag_ids, Tag.all, :id, :name, {},
          {multiple: true, class: 'chosen-select' }
        ) %><br>


      <% if !@question.persisted? && current_user.signed_in_with_twitter? %>
        <%= f.input :tweet_this, as: :boolean%>
      <% else %>
        <br>
      <% end %>
      <%= f.button :submit, class: "btn btn-primary"%>
    <% end %>

<!--    <%= form_for @question do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.collection_select(
          :tag_ids, Tag.all, :id, :name, {},
          {multiple: true, class: 'chosen-select' }
        ) %>
      </div>

      <% if !@question.persisted? && current_user.signed_in_with_twitter? %>
        <div class="form-group">
          <%= f.check_box :tweet_this%>
          <%= f.label :tweet_this %>
        </div>
      <% end %>

      <%# this will automatically generate a submit button. The label for the button
          will depend on the `@question` variable. If @question is a new instance
          then the label of the button will be `Create #{model name capitalized}`.
          If you're not happy with the label, you can pass the label as a first
          arguement: f.submit 'Create'  %>
      <%= f.submit btn_label, class: "btn btn-default" %>
    <% end %> -->
  </div>
</div>
<script>
  $('.chosen-select').chosen({width: '300px'})
</script>

app/views/questions/edit.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-8 col-sm-offset-1">
<h1>Edit Question</h1>
</div>
</div>
<%= render 'form', { btn_label: 'Update' }  %>

app/views/questions/index.html.erb
<h1>All Questions</h1>
<% @questions.each do |q| %>
  <%= image_tag q.image.url(:thumb), class: 'question-thumbnail' %>
  <%= link_to q.title, question_path(q) %>
  <hr>
<% end %>
<div id='paginator'><%= paginate @questions %></div>

app/views/questions/new.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-1">
    <h1>New Question</h1>
  </div>
</div>
<%= render 'form', {btn_label: 'Submit'} %>

app/views/questions/show.html.erb
<div class="row">
  <div class="col-xs-2 col-sm-1">
    <div class="vote-widget">
      <%= upvote_link @question %>
      <h2><%= @question.vote_value %></h2>
      <%= downvote_link @question %>
    </div>
  </div>

  <div class="col-xs-10 col-sm-11 question-show">

    <h1><%= @question.title %></h1>

    <p><%= @question.body %></p>

    <p>
      Created By:  <%= @question.user_full_name %>
    </p>

    <% if can? :manage, @question %>
      <div>
      <%= link_to 'Edit', edit_question_path(@question)%>
      <%= link_to 'Delete', question_path(@question),
                            method: :delete,
                            data: {confirm: 'Are you sure?'}%>
      </div>
    <% end %>

    <% if user_signed_in? && can?(:like, @question)%>
      <% if @like.present? %>
        <%= link_to "Un-Like", like_path(@like), method: :delete %>
      <% else %>
        <%= link_to "Like", question_likes_path(@question), method: :post %>
      <% end %>
    <% end %>
    (<%= pluralize @question.likes.count, "like" %>)



    <section class="tag-widget">
      Tags: <%= @question.tags.map(&:name).join(", ") %>
    </section>
      <%= image_tag @question.image.url %>
    <section>
      <%=  %>
    </section>

  </div>
</div>
<hr/>
<div class="row">
  <div id="answer-form">
    <%= render '/answers/form' %>
  </div>
  <div id='answers'>
    <% @question.answers.each do |answer| %>
      <%= render('/answers/answer', {ans: answer})%>
    <% end %>
  </div>
</div>