config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #when receive get request with / url we invoke index action within
  #home controller
  # get '/' => 'home#index', as: :home
  root 'home#index'
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]
  get '/auth/twitter', as: :sign_in_with_twitter
  get '/auth/twitter/callback' => 'callbacks#twitter'
  namespace :admin do
    resources :questions
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :questions, only: [:index, :show, :create]
    end
  end


  get '/contact' => 'home#contact'
  post '/contact_submit' => 'home#contact_submit'
  resources :users, only: [:create, :new]
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :questions, shallow: true do
    # get :search, on: :collection
    # get :flag, on: :member
    # post :approve
    resources :answers, only: [:create, :destroy] do
      resources :comments, only: [:create, :destroy]
    end

    resources :likes, only: [:create, :destroy]
    resources :votes, only: [:create, :destroy, :update]

  end
  # get '/questions/new'  => 'questions#new', as: :new_question
  # post({'/questions'    => 'questions#create', as: :questions})
  # get '/questions/:id'  => 'questions#show', as: :question
  # get '/questions'      => 'questions#index'
  #
  # get '/questions/:id/edit' => 'questions#edit', as: :edit_question
  # patch '/questions/:id' => 'questions#update'
  # delete '/questions/:id' =>'questions#destroy'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  #this method is called 'action'
  def index
    #render views/home/index.html.erb and use
    #views/layouts/application.html.erb
    #line below is implied by convention
    #render :index
    cookies[:last_visited] = Time.now
    cookies[:lucky_number] = rand(100)
  end

  def contact
  end

  def contact_submit
    @name = params[:full_name]
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contact.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-8 col-sm-offset-1">
    <h1>Contact Us</h1>

<%# form_tag is helpber method that will generate a form HTML element
with POST http request.  The first argument is the url you would like
 to submit the form to.%>

    <%= form_tag contact_submit_path do %>
    <div class="form-group">
      <%= label_tag :full_name %>
      <%= text_field_tag :full_name, nil,  class: "form-control"  %>
    </div>
    <div class="form-group">
      <%= label_tag :email %>
      <%= email_field_tag :email, nil,  class: "form-control"  %>
    </div>
    <div class="form-group">
      <%= label_tag :message %>
      <%= text_area_tag :message, nil,  class: "form-control" %>
    </div>

      <%= submit_tag "Contact Us!", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/home/contact_submit.html.erb
<h1>Thank you <%= @name %> for contacting us</h1>

app/views/home/index.html.erb
<h1>Welcome to Awesome Answers</h1>
<%= image_tag 'friends/stock_image.jpb', style: 'width: 100%' %>