config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #when receive get request with / url we invoke index action within
  #home controller
  # get '/' => 'home#index', as: :home
  root 'home#index'
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]
  get '/auth/twitter', as: :sign_in_with_twitter
  get '/auth/twitter/callback' => 'callbacks#twitter'
  namespace :admin do
    resources :questions
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :questions, only: [:index, :show, :create]
    end
  end


  get '/contact' => 'home#contact'
  post '/contact_submit' => 'home#contact_submit'
  resources :users, only: [:create, :new]
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :questions, shallow: true do
    # get :search, on: :collection
    # get :flag, on: :member
    # post :approve
    resources :answers, only: [:create, :destroy] do
      resources :comments, only: [:create, :destroy]
    end

    resources :likes, only: [:create, :destroy]
    resources :votes, only: [:create, :destroy, :update]

  end
  # get '/questions/new'  => 'questions#new', as: :new_question
  # post({'/questions'    => 'questions#create', as: :questions})
  # get '/questions/:id'  => 'questions#show', as: :question
  # get '/questions'      => 'questions#index'
  #
  # get '/questions/:id/edit' => 'questions#edit', as: :edit_question
  # patch '/questions/:id' => 'questions#update'
  # delete '/questions/:id' =>'questions#destroy'

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :body, presence: true, length: {minimum: 5}

  def user_full_name
    user ? user.full_name : 'Anonymous'
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user

  def create
    @question        = Question.friendly.find params[:question_id]
    answer_params    = params.require(:answer).permit(:body)
    @answer          = Answer.new answer_params
    @answer.question = @question
    @answer.user     = current_user
    respond_to do |format|
      if @answer.save
        AnswersMailer.notify_question_owner(@answer).deliver_later
        format.js {render :create_success}
        format.html do
          redirect_to question_path(@question), notice: 'Answer created!'
        end
      else
        format.js {render :create_failure}
        format.html {render 'questions/show'}
      end
    end
  end

  def destroy
    @answer = Answer.find params[:id]
    respond_to do |format|

      if can? :destroy, @answer
        question = @answer.question
        @answer.destroy
        format.html { redirect_to question, notice: 'Answer deleted!'}
        format.js { render }  #destroy.js.erb by default
      else
        format.html { redirect_to root_path, alert: 'Access Denied'}
        format.js { render js: 'alert("Access denied.")'; }
      end

    end
  end

end

app/helpers/answers_helper.rb
module AnswersHelper

end

app/views/answers/_answer.html.erb
<div class="col-xs-12 answer-container" id="<%= dom_id(ans) %>">
    <div class="col-xs-12">
      <%= ans.user_full_name %> -
    </div>
    <div class="col-xs-11">
      <%= ans.body %>
    </div>
    <div class="col-xs-1">
      <% if can? :delete, ans  %>
        <%= link_to answer_path(ans),
                              remote: true,
                              method: :delete,
                              data: {confirm: 'Are you sure?'},
                              class: "pull-right" do %>
        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
        <% end %>
      <% end %>
    </div>
</div>

app/views/answers/_form.html.erb
<%= @answer.errors.full_messages.join(', ') %>
<div class="col-xs-12">
  <%= form_for [@question, @answer], remote: true do |f| %>
    <div>
      <%= f.text_area :body, class: "form-control", placeholder: "Write your answer!" %>
    </div>
    <%= f.submit class: "btn btn-default"%>
  <% end %>
  <hr/>
</div>

app/views/answers/create_failure.js.erb
$('#answer-form').html('<%= j render 'form' %>');

app/views/answers/create_success.js.erb
$('#answers').prepend("<%= j render 'answer', ans: @answer %>");

<% @answer = Answer.new %>
$('#answer-form').html('<%= j render 'form' %>');

app/views/answers/destroy.js.erb
$("#<%= dom_id(@answer) %>").fadeOut(800, function(){$(this).remove(); });