config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #when receive get request with / url we invoke index action within
  #home controller
  # get '/' => 'home#index', as: :home
  root 'home#index'
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]
  get '/auth/twitter', as: :sign_in_with_twitter
  get '/auth/twitter/callback' => 'callbacks#twitter'
  namespace :admin do
    resources :questions
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :questions, only: [:index, :show, :create]
    end
  end


  get '/contact' => 'home#contact'
  post '/contact_submit' => 'home#contact_submit'
  resources :users, only: [:create, :new]
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :questions, shallow: true do
    # get :search, on: :collection
    # get :flag, on: :member
    # post :approve
    resources :answers, only: [:create, :destroy] do
      resources :comments, only: [:create, :destroy]
    end

    resources :likes, only: [:create, :destroy]
    resources :votes, only: [:create, :destroy, :update]

  end
  # get '/questions/new'  => 'questions#new', as: :new_question
  # post({'/questions'    => 'questions#create', as: :questions})
  # get '/questions/:id'  => 'questions#show', as: :question
  # get '/questions'      => 'questions#index'
  #
  # get '/questions/:id/edit' => 'questions#edit', as: :edit_question
  # patch '/questions/:id' => 'questions#update'
  # delete '/questions/:id' =>'questions#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Awesome Answers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button
            type="button"
            class="navbar-toggle collapsed"
            data-toggle="collapse"
            data-target="#awesome-answers-navbar">
          <span class="glyphicon glyphicon-menu-hamburger"
            aria-hidden="true"></span>
          </button>
          <span
            class="glyphicon glyphicon-question-sign navbar-brand"
            aria-hidden="true"></span>
        </div>
        <div class="navbar-collapse collapse" id="awesome-answers-navbar">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'Contact Us', contact_path %></li>
            <li><%= link_to 'All Questions', questions_path %></li>
            <li><%= link_to 'New Question', new_question_path %></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in?%>
              <li class="navbar-text">
                <p>Hello, <%= current_user.first_name %></p>
              </li>
              <li>
                <%= button_to 'Sign Out',
                  sessions_path,
                  method: :delete,
                  class: "btn btn-default navbar-btn"
                  %>
              </li>
            <% else %>
              <li><%= link_to 'Sign Up', new_user_path %></li>
              <li><%= link_to 'Sign In', new_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <!-- <%= flash[:notice] || flash[:alert]%> -->
    <% if notice || alert %>
      <div class="alert alert-<%=notice ? "success" : "danger"  %> alert-dismissable" role="alert">
        <%= notice || alert %>
        <button
          type="button"
          class="close"
          data-dismiss="alert"
          aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
      </div>
    <% end %>

    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>